import { User, DailyBlessing, BlogPost, Event, Testimonial, FAQ, Service, GalleryItem, Donation, Appointment, MeditationSession, Certificate, DownloadableFile, Notification } from './types';

export const dailyBlessings: DailyBlessing[] = [
  {
    id: '1',
    date: new Date().toISOString().split('T')[0],
    title: 'The Light Within',
    message: 'Just as a lamp dispels darkness, the light of divine knowledge dispels the ignorance of the soul. Seek within, for the Supreme Soul resides in your heart.',
    scripture: 'Bhagavad Gita 10.11',
    reflection: 'Today, take five minutes in silence to connect with the divine light within you.',
    author: 'Gurudev',
  },
  {
    id: '2',
    date: new Date(Date.now() - 86400000).toISOString().split('T')[0],
    title: 'Service to Humanity',
    message: 'The highest form of worship is service to humanity. When you serve others without expectation, you serve the Divine.',
    scripture: 'Rig Veda',
    reflection: 'Perform one act of kindness today without expecting anything in return.',
    author: 'Gurudev',
  },
  {
    id: '3',
    date: new Date(Date.now() - 172800000).toISOString().split('T')[0],
    title: 'Peace of Mind',
    message: 'Peace is not the absence of noise, but the presence of divine consciousness within. Let go of attachments and find tranquility in devotion.',
    scripture: 'Bhagavad Gita 2.66',
    reflection: 'Practice detachment from outcomes today. Focus on your actions, not the results.',
    author: 'Gurudev',
  },
];

export const events: Event[] = [
  {
    id: '1',
    title: 'Divine Satsang with Gurudev',
    type: 'satsang',
    description: 'Join Gurudev for an evening of spiritual discourse, devotional songs, and meditation. Experience the divine presence and elevate your consciousness.',
    date: new Date(Date.now() + 7 * 86400000).toISOString(),
    time: '18:00',
    location: 'BDJJ Ashram, Vrindavan',
    mode: 'hybrid',
    price: 0,
    capacity: 1000,
    registered: 723,
    image: 'https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00?w=800',
    guruId: 'guru1',
    status: 'upcoming',
  },
  {
    id: '2',
    title: 'Meditation Retreat',
    type: 'retreat',
    description: 'A 3-day silent meditation retreat guided by Gurudev. Dive deep into your inner self and experience profound peace.',
    date: new Date(Date.now() + 14 * 86400000).toISOString(),
    time: '06:00',
    endDate: new Date(Date.now() + 17 * 86400000).toISOString(),
    location: 'BDJJ Meditation Center, Rishikesh',
    mode: 'offline',
    price: 5000,
    capacity: 100,
    registered: 67,
    image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800',
    guruId: 'guru1',
    status: 'upcoming',
  },
  {
    id: '3',
    title: 'Festival of Lights Celebration',
    type: 'festival',
    description: 'Celebrate the festival of lights with divine ceremonies, cultural programs, and collective meditation.',
    date: new Date(Date.now() + 30 * 86400000).toISOString(),
    time: '17:00',
    location: 'BDJJ Temple Complex, Delhi',
    mode: 'hybrid',
    price: 0,
    capacity: 5000,
    registered: 2341,
    image: 'https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?w=800',
    guruId: 'guru1',
    status: 'upcoming',
  },
  {
    id: '4',
    title: 'Spiritual Workshop: Art of Living',
    type: 'workshop',
    description: 'Learn practical techniques for managing stress, finding purpose, and living a balanced spiritual life.',
    date: new Date(Date.now() + 21 * 86400000).toISOString(),
    time: '09:00',
    location: 'Online - Zoom',
    mode: 'online',
    price: 999,
    capacity: 500,
    registered: 312,
    image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800',
    guruId: 'guru1',
    status: 'upcoming',
  },
];

export const blogPosts: BlogPost[] = [
  {
    id: '1',
    title: 'The Path of Divine Love',
    slug: 'path-of-divine-love',
    excerpt: 'Discover how unconditional love for the Divine transforms every aspect of your life and leads to ultimate liberation.',
    content: 'Lorem ipsum dolor sit amet...',
    author: 'Gurudev',
    category: 'Spiritual Wisdom',
    tags: ['love', 'devotion', 'liberation'],
    image: 'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?w=800',
    publishedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    readTime: 8,
    featured: true,
  },
  {
    id: '2',
    title: 'Meditation for Beginners',
    slug: 'meditation-for-beginners',
    excerpt: 'A comprehensive guide to starting your meditation practice with simple techniques that anyone can follow.',
    content: 'Lorem ipsum dolor sit amet...',
    author: 'Gurudev',
    category: 'Meditation',
    tags: ['meditation', 'beginners', 'mindfulness'],
    image: 'https://images.unsplash.com/photo-1508672019048-805c876b67e2?w=800',
    publishedAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    readTime: 6,
    featured: true,
  },
  {
    id: '3',
    title: 'Understanding Karma and Dharma',
    slug: 'karma-and-dharma',
    excerpt: 'Ancient wisdom that explains the law of cause and effect and your sacred duty in this lifetime.',
    content: 'Lorem ipsum dolor sit amet...',
    author: 'Gurudev',
    category: 'Spiritual Wisdom',
    tags: ['karma', 'dharma', 'vedanta'],
    image: 'https://images.unsplash.com/photo-1600334129128-685c5582fd35?w=800',
    publishedAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    readTime: 10,
    featured: false,
  },
];

export const testimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Priya Sharma',
    location: 'Mumbai, India',
    content: 'Gurudev\'s teachings transformed my life. I found peace and purpose that I never knew existed. The daily blessings keep me connected to the divine.',
    rating: 5,
    date: '2024-12-15',
  },
  {
    id: '2',
    name: 'Rajesh Kumar',
    location: 'New York, USA',
    content: 'Even from across the world, the BDJJ community makes me feel at home. The online satsangs are truly divine experiences.',
    rating: 5,
    date: '2024-11-28',
  },
  {
    id: '3',
    name: 'Anita Desai',
    location: 'Pune, India',
    content: 'The meditation retreat was a life-changing experience. I learned techniques that help me stay calm and focused every day.',
    rating: 5,
    date: '2024-10-10',
  },
];

export const services: Service[] = [
  {
    id: '1',
    title: 'Personal Spiritual Counseling',
    description: 'One-on-one session with Gurudev for personalized spiritual guidance',
    icon: 'heart',
    price: 0,
    duration: '30 min',
    category: 'counseling',
    available: true,
  },
  {
    id: '2',
    title: 'Group Satsang',
    description: 'Participate in collective devotional gatherings and spiritual discourses',
    icon: 'users',
    price: 0,
    duration: '2 hours',
    category: 'satsang',
    available: true,
  },
  {
    id: '3',
    title: 'Meditation Workshop',
    description: 'Learn advanced meditation techniques for inner peace and spiritual growth',
    icon: 'brain',
    price: 999,
    duration: '3 hours',
    category: 'workshop',
    available: true,
  },
  {
    id: '4',
    title: 'Vedic Blessing Ceremony',
    description: 'Traditional Vedic ceremonies for peace, prosperity, and spiritual well-being',
    icon: 'sparkles',
    price: 2501,
    duration: '1 hour',
    category: 'ceremony',
    available: true,
  },
  {
    id: '5',
    title: 'Home Blessing',
    description: 'Sacred ritual to purify and bless your home with positive energies',
    icon: 'home',
    price: 3501,
    duration: '2 hours',
    category: 'ceremony',
    available: true,
  },
  {
    id: '6',
    title: 'Online Spiritual Course',
    description: 'Structured online course covering spiritual philosophy and daily practices',
    icon: 'book-open',
    price: 1999,
    duration: '4 weeks',
    category: 'course',
    available: true,
  },
];

export const galleryItems: GalleryItem[] = [
  {
    id: '1',
    title: 'Gurudev at Satsang',
    description: 'Divine discourse at BDJJ Ashram',
    type: 'image',
    url: 'https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00?w=800',
    thumbnail: 'https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00?w=400',
    category: 'events',
    uploadedAt: new Date().toISOString(),
  },
  {
    id: '2',
    title: 'Meditation Hall',
    description: 'Peaceful meditation space at the ashram',
    type: 'image',
    url: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800',
    thumbnail: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=400',
    category: 'ashram',
    uploadedAt: new Date().toISOString(),
  },
  {
    id: '3',
    title: 'Festival Celebration',
    description: 'Devotees celebrating together',
    type: 'image',
    url: 'https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?w=800',
    thumbnail: 'https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?w=400',
    category: 'festivals',
    uploadedAt: new Date().toISOString(),
  },
  {
    id: '4',
    title: 'Evening Aarti',
    description: 'Divine evening ceremony',
    type: 'image',
    url: 'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?w=800',
    thumbnail: 'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?w=400',
    category: 'ceremonies',
    uploadedAt: new Date().toISOString(),
  },
  {
    id: '5',
    title: 'Nature at Ashram',
    description: 'Beautiful sunrise over the ashram gardens',
    type: 'image',
    url: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800',
    thumbnail: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=400',
    category: 'ashram',
    uploadedAt: new Date().toISOString(),
  },
  {
    id: '6',
    title: 'Yoga Session',
    description: 'Morning yoga practice with devotees',
    type: 'image',
    url: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800',
    thumbnail: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400',
    category: 'activities',
    uploadedAt: new Date().toISOString(),
  },
];

export const faqs: FAQ[] = [
  {
    id: '1',
    question: 'How do I become a member of BDJJ?',
    answer: 'You can become a member by registering on our website and choosing a membership plan that suits you. Basic membership is free, while Premium and Lifetime memberships offer additional benefits.',
    category: 'membership',
    order: 1,
  },
  {
    id: '2',
    question: 'Are the satsangs free to attend?',
    answer: 'Yes, regular satsangs are free for all members. Some special workshops and retreats may have a nominal fee to cover arrangements.',
    category: 'events',
    order: 2,
  },
  {
    id: '3',
    question: 'Can I donate to BDJJ?',
    answer: 'Yes, you can donate through our website using various payment methods. All donations are tax-exempt under Section 80G of the Income Tax Act.',
    category: 'donations',
    order: 3,
  },
  {
    id: '4',
    question: 'How can I book a personal appointment with Gurudev?',
    answer: 'Members can book appointments through the Member Portal. Appointments are subject to availability and are scheduled on a first-come, first-served basis.',
    category: 'services',
    order: 4,
  },
  {
    id: '5',
    question: 'What is the meditation tracker?',
    answer: 'The meditation tracker is a feature that helps you log your daily meditation practice, track your progress, and earn certificates for achieving milestones.',
    category: 'features',
    order: 5,
  },
  {
    id: '6',
    question: 'How do I cancel my event registration?',
    answer: 'You can cancel your registration from the My Bookings section in your Member Portal. Cancellations made 48 hours before the event are fully refundable.',
    category: 'events',
    order: 6,
  },
];

export const members: User[] = [
  {
    id: 'm1', name: 'Priya Sharma', email: 'priya@example.com', phone: '+91-9876543210',
    role: 'member', membershipId: 'BDJJ-001', membershipType: 'premium',
    membershipExpiry: '2025-12-31', joinedAt: '2024-01-15',
  },
  {
    id: 'm2', name: 'Rajesh Kumar', email: 'rajesh@example.com', phone: '+1-555-1234',
    role: 'member', membershipId: 'BDJJ-002', membershipType: 'lifetime',
    membershipExpiry: '2099-12-31', joinedAt: '2024-02-20',
  },
  {
    id: 'm3', name: 'Anita Desai', email: 'anita@example.com', phone: '+91-8765432109',
    role: 'member', membershipId: 'BDJJ-003', membershipType: 'basic',
    membershipExpiry: '2024-06-30', joinedAt: '2024-03-10',
  },
  {
    id: 'm4', name: 'Vikram Patel', email: 'vikram@example.com', phone: '+91-7654321098',
    role: 'member', membershipId: 'BDJJ-004', membershipType: 'premium',
    membershipExpiry: '2025-06-30', joinedAt: '2024-01-05',
  },
  {
    id: 'm5', name: 'Sunita Verma', email: 'sunita@example.com', phone: '+91-6543210987',
    role: 'member', membershipId: 'BDJJ-005', membershipType: 'basic',
    membershipExpiry: '2024-08-15', joinedAt: '2024-04-22',
  },
];

export const donations: Donation[] = [
  { id: 'd1', userId: 'm1', donorName: 'Priya Sharma', donorEmail: 'priya@example.com', amount: 5001, currency: 'INR', purpose: 'Ashram Development Fund', status: 'completed', date: new Date(Date.now() - 15 * 86400000).toISOString(), anonymous: false },
  { id: 'd2', userId: 'm2', donorName: 'Rajesh Kumar', donorEmail: 'rajesh@example.com', amount: 25000, currency: 'INR', purpose: 'Education for Children', status: 'completed', date: new Date(Date.now() - 30 * 86400000).toISOString(), anonymous: false },
  { id: 'd3', donorName: 'Anonymous', donorEmail: 'anon@example.com', amount: 1100, currency: 'INR', purpose: 'General Donation', status: 'completed', date: new Date(Date.now() - 5 * 86400000).toISOString(), anonymous: true },
  { id: 'd4', userId: 'm3', donorName: 'Anita Desai', donorEmail: 'anita@example.com', amount: 2100, currency: 'INR', purpose: 'Food Distribution', status: 'pending', date: new Date(Date.now() - 1 * 86400000).toISOString(), anonymous: false },
];

export const meditationSessions: MeditationSession[] = [
  { id: 'ms1', userId: 'm1', duration: 20, type: 'guided', completedAt: new Date(Date.now() - 86400000).toISOString(), mood: 'peaceful' },
  { id: 'ms2', userId: 'm1', duration: 15, type: 'breathing', completedAt: new Date(Date.now() - 2 * 86400000).toISOString(), mood: 'calm' },
  { id: 'ms3', userId: 'm1', duration: 30, type: 'silent', completedAt: new Date(Date.now() - 3 * 86400000).toISOString(), mood: 'focused' },
  { id: 'ms4', userId: 'm1', duration: 10, type: 'mantra', completedAt: new Date(Date.now() - 4 * 86400000).toISOString(), mood: 'energetic' },
  { id: 'ms5', userId: 'm1', duration: 25, type: 'guided', completedAt: new Date(Date.now() - 5 * 86400000).toISOString(), mood: 'peaceful' },
];

export const notifications: Notification[] = [
  { id: 'n1', userId: 'm1', title: 'Upcoming Satsang', message: 'Divine Satsang with Gurudev is tomorrow at 6 PM.', type: 'event', read: false, createdAt: new Date(Date.now() - 86400000).toISOString(), link: '/events' },
  { id: 'n2', userId: 'm1', title: 'Donation Received', message: 'Thank you for your generous donation of ₹5,001.', type: 'donation', read: true, createdAt: new Date(Date.now() - 3 * 86400000).toISOString() },
  { id: 'n3', userId: 'm1', title: 'Daily Blessing', message: 'Today\'s blessing: "The Light Within" is now available.', type: 'blessing', read: false, createdAt: new Date(Date.now() - 12 * 3600000).toISOString(), link: '/member/blessings' },
  { id: 'n4', userId: 'm1', title: 'Membership Renewal', message: 'Your premium membership expires in 30 days. Renew now!', type: 'system', read: false, createdAt: new Date(Date.now() - 2 * 86400000).toISOString(), link: '/member/renew' },
  { id: 'n5', userId: 'm1', title: 'New Blog Post', message: 'New article: "The Path of Divine Love" by Gurudev.', type: 'info', read: true, createdAt: new Date(Date.now() - 5 * 86400000).toISOString(), link: '/blog' },
];